## what is object?

** dtype of pandas **

1. int
2. float
3. bool
4. datatime   timedelta
5. category
6. object --- 最高级形式（也可以理解为混合形式）

> Acommadataion of data type in a single column: object is the most general.

## everthing is an object

> Every number, string,data structure, function, class, module, and so on esists in the Python interpreter in its own "box" which is referred to as a Python object. 

> Each object has an associated type( for example, string or functoin_ and internal data.

因为各种都是object，所以在很多methods中可以将 funciton and list or serirs 并列

In [25]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import matplotlib.pyplot as plt

In [26]:
a = DataFrame(np.random.randn(2,3))
a

0         1         2
0  1.215202  0.096511  1.207965
1 -0.254815  0.259501  1.225411

In [27]:
a.dtypes

0    float64
1    float64
2    float64
dtype: object

**information of a:**

每一列是float64的，但整个DataFrame是一个object

## understand dtypes in examples
1 内存大小--反正知道不一样就行, a case in numpy

In [28]:
a = np.random.randn(2)
a.dtype

dtype('float64')

In [29]:
a.dtype = 'float32'
a

array([ -1.24447957e+17,   1.68244600e+00,  -1.37556311e+03,
         1.80508411e+00], dtype=float32)

In [30]:
a.dtype = 'uint8'
a

array([ 97,  16, 221, 219, 100,  90, 215,  63,   5, 242, 171, 196, 255,
        12, 231,  63], dtype=uint8)

** For numpy object, data variate for different dtype **

To fix this problem, **astype** can be used.
> You can use the astype() method to explicitly convert dtype from one to another.

In [31]:
a = np.random.randn(2)
a.astype('float32')

array([ 0.93657982,  0.15771221], dtype=float32)

2 不同dtype有不同内存，对处理数据有什么影响 

In [32]:
s = np.array(['abs','sth'])
s

array(['abs', 'sth'],
      dtype='<U3')

In [33]:
s*2

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U3') dtype('<U3') dtype('<U3')

In [34]:
s = np.array(['abs','sth'],dtype=object)
s*2

array(['absabs', 'sthsth'], dtype=object)

3 [一般对象和object存储方式](./int_object.png)